/*
-- 1. Top 5 Customer Revenue
SELECT CUSTOMERNAME, sum(sales) as [TOTAL REVENUE]
FROM orders
GROUP BY CUSTOMERNAME
ORDER BY [TOTAL REVENUE] DESC
LIMIT 5;

-- 2. Quarter over quarter revenue growth
WITH quarterly AS (
    SELECT
        YEAR_ID,
        QTR_ID,
        SUM(SALES) AS TOTAL_SALES
    FROM orders
    GROUP BY YEAR_ID, QTR_ID
)
SELECT
    YEAR_ID,
    QTR_ID,
    TOTAL_SALES AS CURRENT_SALES,
    LAG(TOTAL_SALES, 1) OVER (ORDER BY YEAR_ID, QTR_ID) AS PREVIOUS_SALES,
    ROUND(
        ((TOTAL_SALES - LAG(TOTAL_SALES, 1) OVER (ORDER BY YEAR_ID, QTR_ID))
        / LAG(TOTAL_SALES, 1) OVER (ORDER BY YEAR_ID, QTR_ID)) * 100,
        2
    ) AS QOQ_GROWTH_PERCENT
FROM quarterly
ORDER BY YEAR_ID, QTR_ID;
*/

-- 3. Product performance by territory 
SELECT 
	PRODUCTCODE
	
	SUM(CASE WHEN TERRITORY = 'APAC' THEN SALES ELSE 0 END) AS APAC_REVENUE,
	SUM(CASE WHEN TERRITORY = 'NA' THEN SALES ELSE 0 END) AS NA_REVENUE,
	SUM(CASE WHEN TERRITORY = 'EMEA' THEN SALES ELSE 0 END) AS EMEA_REVENUE
FROM orders
GROUP BY PRODUCTCODE
ORDER BY PRODUCTCODE;